spring.application.name=ecommerce-livros

# 1. Configuração do Banco de Dados (Apontando para o Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/livros_db
spring.datasource.username=eduardo
spring.datasource.password=1234

# 2. Configurações do JPA (O tradutor Java -> Banco)
# "update": Cria as tabelas se não existirem, e APENAS atualiza se você mudar o código
spring.jpa.hibernate.ddl-auto=update

# Mostra os comandos SQL no terminal (útil para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



